backend:
  name: github
  repo: lablayers/tutheme-boilerplate
  branch: master
media_folder: media
public_folder: /media
collections:
  - name: pages-landing
    label: Landing Pages
    folder: pages/landing
    create: true
    slug: {{slug}}
    fields:
      - {label: "Layout", name: layout, widget: hidden, default: home}
      - {label: "Title", name: title, widget: string, default: Home}
      - {label: "Show Featured Content", name: feature, widget: boolean}
      - {label: "Featured Title", name: featured-title, widget: string}
      - {label: "Featured Image", name: featured-image, widget: image}
      - {label: "Featured Body", name: featured-body, widget: markdown}
      - {label: "Main Content", name: body, widget: markdown}
      - {label: "Show Sidebar", name: sidebar, widget: boolean}
  - name: pages-content
    label: Content Pages
    folder: pages/content
    create: true
    slug: {{slug}}
    fields:
      - {label: "Layout", name: layout, widget: text, default: page}
      - {label: "Title", name: title, widget: string}
      - {label: "Meta Tags", name: meta-keywords, widget: list}
      - {label: "Main Content", name: body, widget: markdown}
      - {label: "Show Sidebar", name: sidebar, widget: boolean}
      - {label: "Sidebar Content", name: sidebar-content, widget: markdown}
